apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${{values.name}}-consumer
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: ${{values.name}}-consumer
  template:
    metadata:
      labels:
        app: ${{values.name}}-consumer
    spec:
      volumes:
        - name: bootstrap
          emptyDir: {}
        - name: cache
          emptyDir: {}
      containers:
        - name: php
          image: ${{values.name}}-consumer:latest
          imagePullPolicy: Never
          resources:
            limits:
              memory: "100Mi"
              cpu: "200m"
          envFrom:
            - configMapRef:
                name: ${{values.name}}
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 82
          volumeMounts:
            - name: bootstrap
              mountPath: /var/www/html/bootstrap/cache
            - name: cache
              mountPath: /var/www/html/storage/framework/cache
